### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by dante-signal31**
Modifications to make vdist runnable from both Python 2.x and Python 3.x.

It passes unit tests and integration tests.

### CODE REVIEW

**Comment by objectified** [comment]
Thanks for your pull request, much appreciated!

Looks good generally, although I'm wondering about one thing: the distinction you made between handling dicts depending on the Python version seems unnecessary, as the Python 3 versions all seem to work with most newer versions of Python 2 as well. So I'd say we could drop the distinction between Python versions there, and simply go with the code you provided for Python 3. Thoughts?

**Comment by dante-signal31** [comment]
I guess you're speaking about commit [9f2f76d](https://github.com/dante-signal31/vdist/commit/9f2f76df433e2a4265ebdac4488fdf8edaf8e724) about line 60.

Python3 and Python2 don't behave the same with dict.items() method. Python2 returns a list so you can use "+" operator but Python3 returns an [iterator](http://stackoverflow.com/questions/10458437/what-is-the-difference-between-dict-items-and-dict-iteritems), so to concatenate two of them you cannot use "+" operator but itertools.chain() instead and materialize the resulting iterator with list() afterwards.

You can try it in console.

With Python 2:

``` python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> dict1 = {"a": 1, "b": 2}
>>> dict2 = {"c": 3, "d": 4}
>>> list3 = dict1.items() + dict2.items()
>>> list3
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
```

With Python 3:

``` python
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
>>> dict1 = {"a": 1, "b": 2}
>>> dict2 = {"c": 3, "d": 4}
>>> list3 = dict1.items() + dict2.items()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
>>> import itertools
>>> list3 = itertools.chain(dict1.items(), dict2.items())
>>> list3
<itertools.chain object at 0x7f29d0c1f828>
>>> type(list3)
<class 'itertools.chain'>
>>> list(list3)
[('b', 2), ('a', 1), ('d', 4), ('c', 3)]
```

That's why you have to keep a distinction between Python2 and Python3 in that part of code.

**Comment by objectified** [comment]
Right, but given that Python 2 also supports the itertools.chain() approach, wouldn't it be easier to drop the Python 2 way altogether instead of making the distinction between 2 and 3? E.g. this works on Python 2 as well:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import itertools
>>> dict1 = {"a": 1, "b": 2}
>>> dict2 = {"c": 3, "d": 4}
>>> dict3 = itertools.chain(dict1.items(), dict2.items())
>>> list(dict3)
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
```

So wouldn't that mean we could choose to go the itertools.chain() route for both Python 2 and 3, without making the distinction?

**Comment by dante-signal31** [comment]
You're right. I've removed distinction in a new commit to the PR. 

All tests (unit and integration) passed in both Python interpreter versions (2 and 3).

**Comment by objectified** [comment]
I've merged your pull request into vdist. Thanks for contributing!

**Pull request merged**
